cart/urls.py
from django.urls import path

from cart.views import cart_detail, cart_add, cart_remove

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('cart_add/<int:product_id>/', cart_add, name='cart_add'),
    path('cart_remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('cart/', include('baskett.urls')),
    path('orders/', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import get_page, page_add_car, detail_info, get_brand, search, registration, login_user, logout_user, \
    kabinet

urlpatterns = [
    path('', get_page, name='home'),
    path('add_car/', page_add_car, name='add_car'),
    path('detail/<int:id>/', detail_info, name='detail_info'),
    path('brand/', get_brand, name='brand'),
    path('search/', search, name='search'),
    path('registration/', registration, name='registration'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('kabinet/', kabinet, name='kabinet'),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.



class AdditionalCarImage(models.Model):
    image = models.ImageField(upload_to="additional_car_image")
    car = models.ForeignKey("Car", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.car.brand} {self.car.model}'


class Car(models.Model):
    brand = models.ForeignKey("Brand", on_delete=models.CASCADE)
    model = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField()
    manufacturer = models.ManyToManyField("Manufacturer")
    image = models.ImageField(upload_to="car_image", blank=True, null=True)

    def __str__(self):
        return f'{self.brand} {self.model}'


class Brand(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Manufacturer(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django.contrib.auth.models import User

from main.models import Car


class AddCarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = "__all__"


class RegistrationForm(forms.ModelForm):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'password2']


    def clean_password2(self):
        cd = self.cleaned_data
        if cd.get('password') != cd.get('password2'):
            raise forms.ValidationError('Введенные пароли не совпадают')
        else:
            return cd.get('password2')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from cart.forms import AddProductForm
from main.forms import AddCarForm, RegistrationForm, LoginForm
from main.models import Car, Brand


# Create your views here.


def get_page(request):
    cars = Car.objects.all()
    brands = Brand.objects.all()
    context = {
        "cars": cars,
        "brands": brands
    }

    return render(request, 'main.html', context)

def get_brand(request):
    brand_cars = Car.objects.filter(brand_id=request.GET.get('brand'))
    context = {
        'cars': brand_cars,
    }
    return render(request, 'brand.html', context)


def page_add_car(request):
    form = AddCarForm()
    if request.method == "POST":
        form = AddCarForm(request.POST, request.FILES)
        if form.is_valid():
            print(form.cleaned_data)
    context = {
        "form": form
    }
    return render(request, 'add_car.html', context)


def detail_info(request, id):
    car = Car.objects.get(id=id)
    form = AddProductForm()
    context = {
        'car': car,
        'form': form
    }
    return render(request, 'detail.html', context)


def search(request):
    context = {

    }
    return render(request, 'search_result.html', context)


def registration(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        print(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            return redirect('home')
    context = {
        'form': form
    }
    return render(request, 'registration.html', context)


def login_user(request):
    form = LoginForm()
    context = {
        'form': form,
    }
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, **form.cleaned_data)
            if user:
                login(request, user)
                return redirect('home')
            else:
                error_message = 'Пользователь с такими данными не найден'
                context = {
                    'form': form,
                    'error_message': error_message
                }
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('home')

def kabinet(request):
    return render(request, 'kabinet.html')

main/templates/add_car.html
{% extends "main.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/add_car.css' %}">
{% endblock %}

{% block content %}
<div class="form_add_car">
    <div class="wrapper">
        <h1 class="add_car_title">
           Добавление автомобиля
        </h1>
        <form action="" method="POST" enctype="multipart/form-data" class="car_form">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" class="save_car_button" value="Отправить">
        </form>
    </div>
</div>
{% endblock %}

main/templates/brand.html
{% extends 'main.html' %}
{% load static %}

main/templates/detail.html
{% extends 'main.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block content %}
<div class="detail_info">
    <div class="wrapper">
        <div class="block_images">
            <div class="main_image">
                <img src="{{ car.image.url }}" alt="">
            </div>
            <div class="additional_images">
                {% for add_image in car.additionalcarimage_set.all %}
                <div class="additional_image">
                    <img src="{{add_image.image.url}}" alt="">
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="block_info">
            <ul class="car_info">
                <li>
                    <h2>{{ car.brand }} {{ car.model }}</h2>
                </li>
                <li>
                    {% for manufacturer in car.manufacturer.all %}
                    {{ manufacturer }}
                    {% endfor %}
                </li>
                <li>
                    {{ car.price }}
                </li>
                <li>
                    {{ car.description }}
                </li>
            </ul>
            <form action="{% url 'cart_add' car.id %}" method="POST">
                {% csrf_token %}
                <table>
                {{form.as_table}}
                    </table>
                <button>Добавить в корзину</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/kabinet.html
{% extends 'main.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static '/css/kabinet.css' %}">
{% endblock %}


{% block content %}

{% endblock %}

main/templates/login.html
{% extends 'main.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static '/css/login.css' %}">
{% endblock %}


{% block content %}
{% if error_message %}
<div class="error_message">
    {{ error_message }}
</div>
{% endif %}
<form action="" method="POST" style="color: black;">
    {% csrf_token %}
    <table>
    {{ form.as_table}}
        </table>
    <button>Войти</button>
</form>
{% endblock %}

main/templates/main.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/null.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %}
    {% endblock %}
    <title>Document</title>
</head>
<body>
<div class="main">
    <div class="main_header">
        <div class="main_header_list">
            <div class="header_left">
                <a href="{% url 'home' %}" class="header_list_logo">
                <img src="{% static 'img/logo.png' %}" alt="">
            </a>
                <div class="header_list_social_account">
                <p class="social_account_title">Социальные сети:</p>
                <ul class="social_account_list">
                    <li class="social_account_item">
                        <a href="#">
                            <img src="{% static 'img/instagram.svg' %}" alt="">
                        </a>
                    </li>
                    <li class="social_account_item">
                        <a href="#">
                            <img src="{% static 'img/telegram.svg' %}" alt="">
                        </a>
                    </li>
                    <li class="social_account_item">
                        <a href="#">
                            <img src="{% static 'img/tiktok.svg' %}" alt="">
                        </a>
                    </li>
                    <li class="social_account_item">
                        <a href="#">
                            <img src="{% static 'img/whatsapp.svg' %}" alt="">
                        </a>
                    </li>
                    <li class="social_account_item">
                        <a href="#">
                            <img src="{% static 'img/youtube.svg' %}" alt="">
                        </a>
                    </li>
                </ul>
            </div>
            </div>
            <div class="header_right">
                <ul class="phone_number_list">
                    <li class="phone_number_item">
                        +375 (29) 111-69-96
                    </li>
                    <li class="phone_number_item">
                        +375 (44) 111-69-96
                    </li>
                    <li class="phone_number_item">
                        +375 (33) 111-69-96
                    </li>
                </ul>
                <div class="authorization">
                    {% if user.is_authenticated %}
                    <a class="authorization_button" href="{% url 'kabinet' %}">{{user.username}}</a>
                    <a class="authorization_button" href="{% url 'logout' %}">Выйти</a>
                    {% else %}
                    <a class="authorization_button" href="{% url 'registration' %}">Регистрация</a>
                    <a class="authorization_button" href="{% url 'login' %}">Авторизация</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="navigation_bar">
            <ul class="navigation_list">
                <li class="navigation_item">
                    <a href="{% url 'add_car' %}">
                        Добавить автомобиль
                    </a>
                </li>
            </ul>
            <div class="brand">
                <form action="{% url 'brand' %}">
                    <select name="brand" id="">
                        {% for brand in brands %}
                        <option value="{{ brand.id }}">
                            {{ brand }}
                        </option>
                        {% endfor %}
                    </select>
                    <button>Отфильтровать</button>
                </form>
            </div>
            <div class="search">
                <form action="{% url 'search' %}" class="search_form">
                    {% csrf_token %}
                    <input type="text" placeholder="Поиск" name="search">
                    <button>Найти</button>
                </form>
            </div>
            <a href="{% url 'cart_detail' %}" class="basket">
                <div class="basket_img">
                    <img src="{% static 'img/basket.png' %}" alt="">
                </div>
                <p>
                    {{ cart|length }}
                </p>
            </a>

    </div>
    <div class="list_card">
    {% block content %}

        <div class="list_wrapper">
            {% for car in cars %}
            <article>
                <a href="{% url 'detail_info' car.id %}" class="card">
                    <div class="card_img">
                        <img src="{{ car.image.url }}" alt="">
                    </div>
                    <p class="card_title">
                        {{ car.brand }} {{ car.model }}
                    </p>
                    <p class="card_price">
                        {{ car.price }}$
                    </p>
                </a>
            </article>
            {% endfor %}
        </div>

    {% endblock %}
        </div>
</div>
</body>
</html>

main/templates/registration.html
{% extends 'main.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static '/css/registration.css' %}">
{% endblock %}


{% block content %}
<form action="" method="POST" style="color: black;">
    {% csrf_token %}
    <table>
    {{ form.as_table}}
        </table>
    <button>Зарегистрироваться</button>
</form>
{% endblock %}

main/templates/search_result.html
{% extends 'main.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static '/css/search_result.css' %}">
{% endblock %}